import type { OrderView, StationFlavor } from "@ocs/core";
import Link from "next/link";

function money(order: OrderView): Intl.NumberFormat {
  return new Intl.NumberFormat(order.flavor === "cn" ? "zh-CN" : "en-US", { style: "currency", currency: order.currency });
}

export function MerchantOrderList({ flavor, orders }: { readonly flavor: StationFlavor; readonly orders: readonly OrderView[] }) {
  const zh = flavor === "cn";
  return <section><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-800">Orders</p><h1 className="mt-3 text-4xl font-bold">{zh ? "订单" : "Orders"}</h1><p className="mt-3 text-stone-600">{zh ? "订单事实来自支付时快照；后续商品或配送配置变化不会改写历史订单。" : "Order facts are snapshotted at payment and do not change with later catalog or shipping edits."}</p>{orders.length === 0 ? <div className="mt-8 rounded-3xl border border-stone-200 bg-white p-7 text-stone-500">{zh ? "暂无已支付订单。" : "No paid Orders yet."}</div> : <div className="mt-8 overflow-hidden rounded-3xl border border-stone-200 bg-white"><div className="hidden grid-cols-[1.2fr_1fr_0.7fr_0.8fr] gap-4 border-b border-stone-200 bg-stone-50 px-6 py-3 text-xs font-bold uppercase tracking-wide text-stone-500 md:grid"><span>{zh ? "订单" : "Order"}</span><span>{zh ? "顾客" : "Shopper"}</span><span>{zh ? "履约" : "Fulfillment"}</span><span className="text-right">{zh ? "总计" : "Total"}</span></div>{orders.map((order) => <Link key={order.number} href={`/portal/orders/${order.number}`} className="grid gap-3 border-b border-stone-100 px-6 py-5 last:border-0 hover:bg-stone-50 md:grid-cols-[1.2fr_1fr_0.7fr_0.8fr] md:items-center"><div><p className="font-mono text-sm font-bold">{order.number}</p><p className="mt-1 text-xs text-stone-500">{new Intl.DateTimeFormat(zh ? "zh-CN" : "en-US", { dateStyle: "medium", timeStyle: "short" }).format(order.createdAt)}</p></div><p className="truncate text-sm">{order.shopperEmail}</p><p className="text-sm font-semibold">{order.fulfillmentStatus}</p><p className="font-bold md:text-right">{money(order).format(order.totalMinor / 100)}</p></Link>)}</div>}</section>;
}

export function MerchantOrderDetail({ order }: { readonly order: OrderView }) {
  const zh = order.flavor === "cn";
  const format = money(order);
  return <section><Link href="/portal/orders" className="text-sm font-semibold underline underline-offset-4">← {zh ? "全部订单" : "All Orders"}</Link><div className="mt-6 rounded-3xl border border-stone-200 bg-white p-7"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-800">Order Detail</p><h1 className="mt-3 font-mono text-3xl font-bold">{order.number}</h1><p className="mt-2 text-sm text-stone-500">{order.shopperEmail}</p></div><div className="text-right"><p className="text-2xl font-bold">{format.format(order.totalMinor / 100)}</p><p className="mt-2 text-sm">{order.paymentStatus} · {order.fulfillmentStatus}</p></div></div><div className="mt-8 grid gap-8 border-t border-stone-200 pt-7 md:grid-cols-2"><div><h2 className="font-bold">{zh ? "商品快照" : "Line snapshots"}</h2><div className="mt-4 space-y-4">{order.lines.map((line) => <div key={line.variantReference} className="flex justify-between gap-4 text-sm"><div><p className="font-semibold">{line.productName[zh ? "zh" : "en"] ?? line.productSlug}</p><p className="text-stone-500">{line.variantLabel || "single"} × {line.quantity}</p></div><p>{format.format(line.lineSubtotalMinor / 100)}</p></div>)}</div></div><address className="not-italic text-sm leading-7 text-stone-600"><h2 className="mb-2 font-bold text-stone-950">{zh ? "配送地址快照" : "Address snapshot"}</h2>{order.address.recipientName} · {order.address.phone}<br />{order.address.countryCode} {order.address.region} {order.address.city} {order.address.district}<br />{order.address.line1} {order.address.line2}<br />{order.address.postalCode}</address></div></div></section>;
}
