import { pickLocalizedText } from "@ocs/core";
import type { ReservedPolicy, StationFlavor } from "@ocs/core";

interface PolicyManagerProps { readonly flavor: StationFlavor; readonly policies: readonly ReservedPolicy[]; readonly saveAction: (formData: FormData) => void | Promise<void>; readonly saved?: boolean; readonly error?: boolean; }
const copy = { cn: { eyebrow: "商家后台 · 说明", title: "店铺说明", intro: "四篇说明始终出现在店面与结账；正文留空不会阻止收款，但会显示尚未填写。", body: "正文", save: "保存说明", saved: "说明已保存。", error: "没有保存：正文过长或字段无效。" }, global: { eyebrow: "Merchant Portal · Policies", title: "Store Handbook", intro: "These four Policies always appear on the Storefront and Checkout. Empty content does not block payment and is labeled as unfinished.", body: "Body", save: "Save Policy", saved: "Policy saved.", error: "Not saved: the body is too long or invalid." } } as const;
export function PolicyManager({ flavor, policies, saveAction, saved, error }: PolicyManagerProps) {
  const labels = copy[flavor]; const locale = flavor === "cn" ? "zh" : "en";
  return <section><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-800">{labels.eyebrow}</p><h1 className="mt-3 font-[family-name:var(--font-display)] text-4xl font-semibold tracking-[-0.035em]">{labels.title}</h1><p className="mt-3 max-w-2xl leading-7 text-stone-600">{labels.intro}</p>{saved ? <p role="status" className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{labels.saved}</p> : null}{error ? <p role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-900">{labels.error}</p> : null}<div className="mt-8 grid gap-5 lg:grid-cols-2">{policies.map((policy) => <form key={policy.slug} action={saveAction} className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm md:p-7"><input type="hidden" name="slug" value={policy.slug} /><h2 className="font-[family-name:var(--font-display)] text-2xl font-semibold">{pickLocalizedText(policy.title, locale, locale)}</h2><label className="mt-4 block text-xs font-semibold text-stone-600">{labels.body}<textarea name="body" rows={10} maxLength={100_000} defaultValue={pickLocalizedText(policy.body, locale, locale)} className="mt-2 block w-full resize-y rounded-xl border border-stone-300 px-4 py-3 text-sm leading-6 text-stone-950" /></label><button className="mt-4 rounded-full bg-stone-950 px-5 py-2.5 text-sm font-bold text-white">{labels.save}</button></form>)}</div></section>;
}
