import { pickLocalizedText } from "@ocs/core";
import type { ShippingRateView, StationFlavor } from "@ocs/core";

interface ShippingManagerProps { readonly flavor: StationFlavor; readonly rates: readonly ShippingRateView[]; readonly saveAction: (formData: FormData) => void | Promise<void>; readonly deleteAction: (formData: FormData) => void | Promise<void>; readonly saved?: boolean; readonly error?: boolean; }
const copy = {
  cn: { eyebrow: "商家后台 · 配送", title: "运费规则", intro: "按省份、购物车总重量与优惠后金额匹配；顾客必须选中一种配送才能继续。", name: "名称", countries: "国家代码（逗号）", regions: "省份（逗号，空=全部）", min: "最小克重", max: "最大克重", price: "运费（元）", free: "满额免邮（元）", pos: "排序", active: "启用", create: "新建配送", save: "保存", remove: "删除", saved: "运费规则已保存。", error: "没有保存：请检查地区、重量与金额。" },
  global: { eyebrow: "Merchant Portal · Shipping", title: "Shipping Rates", intro: "Match by country, region, total Cart weight, and post-discount amount. Checkout needs one valid Rate.", name: "Name", countries: "Country codes (comma)", regions: "Regions (comma, blank=all)", min: "Min grams", max: "Max grams", price: "Price (USD)", free: "Free over (USD)", pos: "Position", active: "Enabled", create: "New Rate", save: "Save", remove: "Delete", saved: "Shipping Rate saved.", error: "Not saved: check regions, weight, and amounts." },
} as const;

function Fields({ flavor, rate }: { readonly flavor: StationFlavor; readonly rate?: ShippingRateView }) {
  const labels = copy[flavor]; const locale = flavor === "cn" ? "zh" : "en";
  return <>{rate ? <input type="hidden" name="id" value={rate.id} /> : null}<label className="text-xs font-semibold text-stone-600">{labels.name}<input name="name" required defaultValue={rate ? pickLocalizedText(rate.name, locale, locale) : ""} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2 text-sm text-stone-950" /></label><label className="text-xs font-semibold text-stone-600">{labels.countries}<input name="countries" defaultValue={rate?.countryCodes.join(", ") ?? (flavor === "cn" ? "CN" : "")} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2 text-sm text-stone-950" /></label><label className="text-xs font-semibold text-stone-600">{labels.regions}<input name="regions" defaultValue={rate?.regions.join(", ") ?? ""} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2 text-sm text-stone-950" /></label><label className="text-xs font-semibold text-stone-600">{labels.min}<input name="minWeightGrams" type="number" min="0" step="1" required defaultValue={rate?.minWeightGrams ?? 0} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2 text-sm text-stone-950" /></label><label className="text-xs font-semibold text-stone-600">{labels.max}<input name="maxWeightGrams" type="number" min="0" step="1" defaultValue={rate?.maxWeightGrams ?? ""} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2 text-sm text-stone-950" /></label><label className="text-xs font-semibold text-stone-600">{labels.price}<input name="price" type="number" min="0" step="0.01" required defaultValue={rate ? (rate.priceMinor / 100).toFixed(2) : ""} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2 text-sm text-stone-950" /></label><label className="text-xs font-semibold text-stone-600">{labels.free}<input name="freeOver" type="number" min="0.01" step="0.01" defaultValue={rate?.freeOverMinor ? (rate.freeOverMinor / 100).toFixed(2) : ""} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2 text-sm text-stone-950" /></label><label className="text-xs font-semibold text-stone-600">{labels.pos}<input name="position" type="number" min="0" step="1" required defaultValue={rate?.position ?? 0} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2 text-sm text-stone-950" /></label><label className="flex items-center gap-2 pb-2 text-sm font-semibold"><input name="enabled" type="checkbox" defaultChecked={rate?.enabled ?? true} className="size-4 accent-emerald-700" />{labels.active}</label></>;
}

export function ShippingManager({ flavor, rates, saveAction, deleteAction, saved, error }: ShippingManagerProps) {
  const labels = copy[flavor];
  return <section><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-800">{labels.eyebrow}</p><h1 className="mt-3 font-[family-name:var(--font-display)] text-4xl font-semibold tracking-[-0.035em]">{labels.title}</h1><p className="mt-3 max-w-3xl leading-7 text-stone-600">{labels.intro}</p>{saved ? <p role="status" className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{labels.saved}</p> : null}{error ? <p role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-900">{labels.error}</p> : null}<form action={saveAction} className="mt-8 grid gap-4 rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-5 lg:items-end md:p-7"><Fields flavor={flavor} /><button className="rounded-full bg-stone-950 px-5 py-2.5 text-sm font-bold text-white">{labels.create}</button></form><div className="mt-6 space-y-4">{rates.map((rate) => <div key={rate.id} className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm"><form action={saveAction} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5 lg:items-end"><Fields flavor={flavor} rate={rate} /><button className="rounded-full border border-stone-300 px-4 py-2 text-sm font-semibold">{labels.save}</button></form><form action={deleteAction} className="mt-3 text-right"><input type="hidden" name="id" value={rate.id} /><button className="text-sm font-semibold text-red-700">{labels.remove}</button></form></div>)}</div></section>;
}
